# Q3. Singular Value Decomposition (SVD):
Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print matrices U, Σ, and V.Verify that A equals the product of U, Σ, and 𝑉. Additionally, find the rank 2 and rank 3 approximations of matrix A.



In [3]:
import numpy as np
np.random.seed(60)
A = np.random.randint(0, 10, size=(5, 5))

In [4]:
# Perform Singular Value Decomposition (SVD)
U,Sigma,V_transpose = np.linalg.svd(A)
Sigma_mat = np.zeros_like(A, dtype=float)
Sigma_mat[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(Sigma)
print("Matrix U:")
print(U)
print("\nMatrix Sigma:")
print(Sigma_mat)
print("\nMatrix V:")
print(V_transpose.T)

Matrix U:
[[-0.55898614 -0.33431486 -0.0128476  -0.06776356  0.75565277]
 [-0.41666458 -0.37737864  0.62726318  0.31673503 -0.43611445]
 [-0.40277372  0.80293318  0.3658017  -0.23978454  0.04200155]
 [-0.26158423 -0.26824743 -0.19174982 -0.81950082 -0.38893113]
 [-0.53223317  0.17076463 -0.6601492   0.40744178 -0.29285069]]

Matrix Sigma:
[[24.24434244  0.          0.          0.          0.        ]
 [ 0.          7.83724526  0.          0.          0.        ]
 [ 0.          0.          4.15210728  0.          0.        ]
 [ 0.          0.          0.          3.58215939  0.        ]
 [ 0.          0.          0.          0.          0.84710418]]

Matrix V:
[[-0.14488691  0.35299106  0.49611541 -0.72273525 -0.29313537]
 [-0.3916012  -0.1877483  -0.72507764 -0.53195114  0.05186022]
 [-0.35097721  0.77421719 -0.10735783  0.17861258  0.48370919]
 [-0.63437624  0.02980245 -0.00812131  0.40333299 -0.65873754]
 [-0.54775731 -0.48974222  0.46533886 -0.01008883  0.49342927]]


In [6]:
A_reconstructed = np.dot(U, np.dot(Sigma_mat, V_transpose))
print("Verification that A equals the product of U, Sigma, and V:")
print(np.allclose(A, A_reconstructed))

Verification that A equals the product of U, Sigma, and V:
True
